# Generated by Django 3.1.5 on 2021-01-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
