# Generated by Django 3.1.5 on 2021-01-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientApp', '0002_auto_20210109_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
